name: qs_blocs
description: QS Blocs
version: 0.0.5
homepage: 'https://github.com/artsiombarouski/qs_blocs'

environment:
  sdk: ">=2.17.0-0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  connectivity_plus: ^6.1.0
  synchronized: ^3.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
