name: qs_blocs
description: QS Blocs
version: 0.0.4
homepage: 'https://github.com/artsiombarouski/qs_blocs'

environment:
  sdk: ">=2.17.0-0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  connectivity_plus: ^2.3.0
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.0.5
