name: qs_blocs
description: QS Blocs
version: 0.0.1
homepage: '???'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: ^2.0.3
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.5
